### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by Dawnbrightsu** [gildedgames/gilded-games-util#20]
solved

**Comment by jellysquid3** [comment]
> This error occurs when running the setup.exe.

We don't provide a setup.exe, unless you're referring to `setup.bat`.

Regardless-- Gilded Games Util is in a very poor state right now, and shouldn't be used (it doesn't surprise me that it's not even compiling). Is there a specific reason you need a compiled version of GGUtil?
